on: [push,pull_request]

jobs:
   mypy-pep8:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy flake8
    - name: Mypy
      run: |
        # Replace src/ with the path to your Python source code
        mypy *.py
    - name: Flake8
      run: |
        # Replace src/ with the path to your Python source code
        flake8 *.py
